### ISSUE TITLE
paymentCurrency vs. currency

### ISSUE THREAD

**Issue by engram-design** [newism/commerce-afterpay#13]
We're getting an error on a multi-site, multi-currency install:

```
Client error: `POST https://api-sandbox.afterpay.com/v1/orders` resulted in a `422 Unprocessable Entity` response:
{
"errorCode" : "unsupported_currency",
"errorId" : "c613326b60e14219",
"message" : "An error occurred",
"httpSt (truncated...)
```

We're following https://craftcms.com/docs/commerce/3.x/payment-currencies.html#switching-currencies by setting the paymentCurrency for an order, for a particular site. Commerce's currency handling seems a bit odd, where you can't set the `order->currency`. See https://github.com/craftcms/commerce/issues/790

The primary site's currency is in GBP, but we're on the AU site, trying to pay in AUD (`paymentCurrency` is set to `AUD`). I believe you just can't change the `currency` attribute on an order, and it'll be whatever your primary currency is. So the error is valid, GBP isn't supported.

Any reason for using the `currency` over the order's `paymentCurrency`? Changing this works.

**Comment by leevigraham** [comment]
> Any reason for using the currency over the order's paymentCurrency? Changing this works.

Probably Commerce 2. I'll have to check the PR on both versions.
