### ISSUE TITLE
Afterpay > Clearpay

### ISSUE THREAD

**Issue by bymayo** [newism/commerce-afterpay#2]
We have an AUS client that wants to use this gateway on their site, but also wants to integrate it with EUR also. 

I originally didn't think it existed for EUR, but after doing some research Afterpay does exist, but in EUR it is called Clearpay (Some legal rubbish) - So will this work for both, as it's the same company?

Or would I be looking at a different plugin?

https://docs.afterpay.com/uk-online-api-v1.html

**Comment by leevigraham** [comment]
Hi @bymayo Looks like the endpoints are the same so it might work. You will need to fork the repo and add the new UK endpoints here: https://github.com/newism/commerce-afterpay/blob/master/src/gateways/AfterpayGateway.php#L41

If it works a PR would be awesome.

**Comment by bymayo** [comment]
Okay perfect, I did look at that file and notice the endpoints array. We're just waiting for the work to be confirmed, then we'll work on this and i'll add the endpoint to the array and test. Then i'll do a PR

**Comment by bymayo** [comment]
@leevigraham Is there any issues with this plugin not being _approved_ by Afterpay? 

Before we started this PR request, we had our client contact us and CC AfterPay in to say that they have not approved the plugin on their end, so it's unlikely to work!? Sounds crazy to me. But wasn't sure if you'd heard anything like this.

**Comment by leevigraham** [comment]
If you have an Afterpay merchant account there's no reason why this shouldn't still work. The implementation of the API is up to the developer. As long as it matches the API you should be all good. My guess is they're just protecting themselves.

**Comment by bymayo** [comment]
@leevigraham That was my thinking. Bit silly how they are saying we can't use this plugin because it's not _verified_. I'll let the client know, and I'll see what AfterPay say.
