### ISSUE TITLE
Missing brackets in Settings.twig

### ISSUE THREAD

**Issue by emilyfitton** [newism/commerce-afterpay#21]
Version 2.2. has some brackets missing in vendor/newism/commerce-afterpay/src/templates/gateway/settings.twig.html

![chrome_2020-11-24_11-30-04](https://user-images.githubusercontent.com/5026556/100033498-73cbe080-2e4e-11eb-84d9-72f929419a46.png)

Solution: Add 
`}) }}`
to line 42

![image](https://user-images.githubusercontent.com/5026556/100033701-cb6a4c00-2e4e-11eb-922e-8d82e33f3f78.png)

**Comment by leevigraham** [comment]
Thanks @emilyfitton, Fixed: https://github.com/newism/commerce-afterpay/releases/tag/2.2.1

**Comment by leevigraham** [comment]
Commit: https://github.com/newism/commerce-afterpay/commit/c287e4653c6ddd497afa580e9cf76c236f3c3679
