### ISSUE TITLE
JS Error on redirect

### ISSUE THREAD

**Issue by engram-design** [newism/commerce-afterpay#27]
I'm getting the following error on the step before redirect.

![image](https://user-images.githubusercontent.com/1221575/132937730-9d9fa313-7d4b-427c-9a20-fc714ad7365d.png)

This seems like a valid error, but I've got this plugin on a few sites now with no issue. I'm not sure what the deal is there, because I can't see how this **wouldn't** be an issue! It's plain invalid JS, as it's missing a `}`.

`AfterPay.initialize({countryCode: {{ region }});`

vs

`AfterPay.initialize({countryCode: "{{ region }}"});`

**Comment by leevigraham** [comment]
https://github.com/newism/commerce-afterpay/releases/tag/2.2.3
