### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by bymayo** [newism/commerce-afterpay#3]
Not sure why but I can't install this plugin either through the plugin store or composer. I get the error:

```
  [InvalidArgumentException]                                                                                                                                                                                               
  Could not find a matching version of package newism/commerce-afterpay. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stabl  
  e). 
```

I checked Packagist and it does look like the package doesn't exist. Is this a mistake?

I finally got round to convincing the client to use this plugin and it won't install! 😂

**Comment by leevigraham** [comment]
@bymayo Hmm weird. It should be in packagist in order to get it in the Craft store. Not sure what happened there… I'll take a look.

In the mean time you can install it by adding a repo… 

https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

**Comment by leevigraham** [comment]
Now on packagist: https://packagist.org/packages/newism/commerce-afterpay

**Comment by bymayo** [comment]
I did check on Packagist but could only find another Craft3 AfterPay by another developer!

Thanks for adding it 💯

**Comment by bymayo** [comment]
I don't know if this is related, but when I now try to install the plugin it hangs at `enabling plugin` with a 500 error in console. 

When I then try to manually enable this in `admin/settings/plugins` I get the error:

`No plugin exists with the handle "newism-commerce-afterpay".`

I've tried rebuilding the `vendor` folder, and used `composer clear-cache` just incase it was an error with that.

I also noticed that the plugin is in the `vendor` folder and in your `composer.json` file it has the handle of `newism-commerce-afterpay`!!! 

I'm super stumped!

**Comment by leevigraham** [comment]
@bymayo I'll test everything again tonight and make sure it's all sweet.

**Comment by bymayo** [comment]
@leevigraham It does seem to all be correct - Except for that one project where I had the issue where it couldn't find the package.

I'm totally confused as to why it won't 'Enable' though. But I think this is a Craft issue, so I'll get in touch with them.

UPDATE:

I was right, it was just a Craft issue. Running `./craft project-config/rebuild` fixes the issue and I can install the plugin! 🎉
