### ISSUE TITLE
Orders being marked as paid before completing Afterpay transaction.

### ISSUE THREAD

**Issue by jasonwoodland** [newism/commerce-afterpay#4]
I'm having an issue where orders are immediately being marked as paid when the user is redirected to the Afterpay checkout.

I basically redirect the user to checkout by submitting a form with:
```
        <input type="hidden" name="action" value="commerce/payments/pay">
        {% nocache %}
          {{ csrfInput() }}
        {% endnocache %}
        {{ redirectInput('/checkout/order?number='~cart.number) }}
        <input type="hidden" name="cancelUrl" value="{{ '/checkout/payment'|hash }}"/>
```

Also if I click cancel on the Afterpay checkout my `cancelUrl` is not respected and I am redirected to `SITE_URL`

Here is the transaction information for the order, even though I didn't complete a transaction.

![Screen Shot 2020-03-24 at 4 50 09 pm](https://user-images.githubusercontent.com/5356544/77392638-88536700-6def-11ea-8841-c7cc75927daf.png)

**Comment by leevigraham** [comment]
Fixed in b9d9ea2
