### ISSUE TITLE
Invalid/Improperly formatted JSON in submission in Commerce 3.0

### ISSUE THREAD

**Issue by dwhoban** [newism/commerce-afterpay#9]
When checking out with Afterpay on Commerce 3 payment always fails due to `errorCode: "invalid_json"` regardless of product details.

Error response is also truncated so there is limited information.

```
 Client error: `POST https://api-sandbox.afterpay.com/v1/orders` resulted in a `400 Bad Request` response: { "errorCode" : "invalid_json", "errorId" : "03dcc4e24f5a671c", "message" : "The request contains improperly forma (truncated...) 
```

**Comment by leevigraham** [comment]
Hmm… I'll take a look in my test setup, can you breakpoint in the gateway to provide the full error?

**Comment by dwhoban** [comment]
@leevigraham struggling to get the right breakpoint to deliver the full error.  For some reason I did get an complete purchase through but then it is failing again - there may be something in the name of the products that is not encoding properly.

**Comment by dwhoban** [comment]
@leevigraham managed to find it with some help - the Total Tax of an order can return a value with more than 2 decimal points.

**Comment by leevigraham** [comment]
New Release: https://github.com/newism/commerce-afterpay/releases/tag/2.0.1
